version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      # Você pode definir o token aqui para o ambiente de produção/deploy
      # Lembre-se de usar secrets do seu provedor de hospedagem em um cenário real
      - API_TOKEN=${API_TOKEN}